### ISSUE TITLE
Add users

### ISSUE THREAD

**Issue by half-ogre** [half-ogre/qed#5]
The following actions should only be available to approved users:
- starting a build manually (i.e., not through a web hook)
- building a PR (for security reasons)
- re-building a failed build

Anyone should be able to view the home page, `/builds`, and `/builds/{id}`.
## To-Do (v0.1)
- [x] #55: let anyone sign up (i.e., create a user account)
- [x] #56: let users sign in
- [x] #57: let users sign out
- [x] #59: let administrators make other users administrators
- [x] #58: only let administrators start builds
- [x] #66: Require an initial administrator
## To-Do (vLater)
- [ ] require email confirmation
- [ ] let users reset their password via email
- [ ] let users change their password
- [ ] let administrators invite new users
